# Generated by Django 6.0 on 2026-04-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='tmdb_id',
            field=models.IntegerField(blank=True, help_text='ID de TMDB para evitar duplicados', null=True, unique=True),
        ),
    ]
