# Generated by Django 6.0 on 2026-04-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_serie_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='imagen_respaldo',
            field=models.CharField(blank=True, help_text='Ruta a imagen local de respaldo', max_length=200, null=True),
        ),
    ]
