# Generated by Django 6.0 on 2026-04-26 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_serie_imagen_respaldo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='usuarios_que_guardaron',
            field=models.ManyToManyField(blank=True, related_name='series_guardadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
