# Generated by Django 6.0 on 2026-04-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_serie_usuarios_que_guardaron'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='tipo',
            field=models.CharField(default='tv', help_text='tv o movie', max_length=10),
        ),
    ]
