# Generated by Django 6.0 on 2026-05-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_serie_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='tmdb_id',
            field=models.IntegerField(blank=True, help_text='ID de TMDB', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='serie',
            unique_together={('tmdb_id', 'tipo')},
        ),
    ]
